---
- hosts: all
  user: vagrant
  sudo: yes
  vars_files:
    - vars/defaults.yml

  roles:
    - webserver
    - database

  handlers: 
    - name: Restart puma
      action: service name=puma state=restarted
